name: PyLint

on:
  push:
    branches:
      - main  

jobs:
  lint:
    name: Run PyLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install pylint

      - name: Run PyLint
        run: pylint python_w_poetry, tests

      - name: Upload PyLint Report
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: pylint.log  # Replace with the path to your PyLint report
